### PR TITLE
upgrade to node-postal 1.0.0

### PR DESCRIPTION
**Pull request by missinglink**
upgrade to `node-postal@1.0.0`

fixes #54

### CODE REVIEW

**Comment by missinglink** [comment]
rebased, trying Travis again

**Comment by missinglink** [comment]
@orangejulius the Travis message now is about `@mapbox/polyline`, it seems like it's not getting correctly installed?

```bash
@mapbox/polyline   NOTUSED?  Still using @mapbox/polyline?
                             Depcheck did not find code similar to require('@mapbox/polyline') or import from '@mapbox/polyline'.
                             Check your code before removing as depcheck isn't able to foresee all ways dependencies can be used.
                             Use --skip-unused to skip this check.
                             To remove this package: npm uninstall --save @mapbox/polyline
polyline           MISSING!  Not installed.
                   PKG ERR!  Not in the package.json. Found in: /api/near.js, /cmd/server.js, /lib/Street.js, /stream/address/augment.js, /stream/osm/augment.js, /stream/vertices/augment.js, /test/lib/project.js, /test/lib/proximity.js
Use npm-check -u for interactive update.
```

**Comment by missinglink** [comment]
rebased master to bring in Travis configuration

**Comment by missinglink** [comment]
looks like this will require re-running the script which generates the mock libpostal responses

**Comment by orangejulius** [comment]
Hmm. I was able to update the mock libpostal responses, but am getting lots of errors in the tests that seem unrelated. Here's some of them. Maybe we can take a look at it tomorrow.
screenshot from 2017-05-31 14-50-37

**Pull request merged**
