### PR TITLE
[WIP] prevent performance degration when no double quote in the lines

### PR DESCRIPTION
**Pull request by slvlirnoff**
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.

---
#### Here's the reason for this change :rocket:

It improves on #211 

---
#### Here's what actually got changed :clap:

I've added some field with quotes to each csv lines. Otherwise awk eat a awful lots of memory and time.

---
#### Here's how others can test the changes :eyes:

With my quick testing it seems to work properly. However someone more aware of this project / awk could propose a better fix.

### CODE REVIEW

**Comment by missinglink** [comment]
On reflection, maybe AWK wasn't the best tool to choose, how about we rewrite this in JavaScript?

**Comment by slvlirnoff** [comment]
Yes, here maybe simply fixing the parser to accept new lines within quoted string would be easier. I have a feeling this proposed fixed doesn't work well in some cases.

**Comment by orangejulius** [comment]
Hi @slvlirnoff,

Thanks for opening this PR. The interpolation service can definitely be slow to import and we have identified this set of sed/awk invocations as taking a lot of CPU in the past. Its code that feels like it _must_ be possible to improve but we haven't gotten around to it, and there are definitely a lot of legitimate issues the code solves.

I tried running your code on the Italy countrywide file (from https://data.openaddresses.io/runs/676763/it/countrywide.zip) and didn't see any change in the time to run the `oa_concat.sh` script (it was around 2 minutes on both your branch and master).

Can you try that exact file and see if you get the same behavior, and also send the file you currently have if it's different? Maybe only some files are susceptible to this issue.

**Comment by slvlirnoff** [comment]
Hi @orangejulius 

On the file you linked to, I've run the awk command (the same as in oa_concat.sh), see how the time increase exponentially with the number of lines read?

Then the last line is with including some extra quote on each line, preventing I guess awk from concatenating the output over and over until reaching the end of the file. The whole file takes a few hours on my server to complete.

It might be linked to awk version? Architecture (i9-9900k)?

I'm pretty confident my fix isn't working and breaking the import of some files, so I would suggest to close this merge request and make a proper fix. However this seems a huge drop of performance for some of the files.

Best,
Cyprien

```
root@Debian-100-buster-64-minimal /data/test # awk -W version                                                                                                                                          
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan                                                                                                                                                  
                                                                                                                                                                                                       
compiled limits:                                                                                                                                                                                       
max NF             32767                                                                                                                                                                               
sprintf buffer      2040                                                                                                                                                                               

root@Debian-100-buster-64-minimal /data/test # time tail -n 100000 it/countrywide.csv | awk -v RS='"' 'NR % 2 == 0 { gsub(/\r?\n|\r/, " ") } { printf("%s%s", $0, "\r") }' > /dev/null                  
                                                                                                                                                                                                       
real    0m0.240s                                                                                                                                                                                       
user    0m0.245s                                                                                                                                                                                       
sys     0m0.017s                                                                                                                                                                                       
root@Debian-100-buster-64-minimal /data/test # time tail -n 200000 it/countrywide.csv | awk -v RS='"' 'NR % 2 == 0 { gsub(/\r?\n|\r/, " ") } { printf("%s%s", $0, "\r") }' > /dev/null                  
                                                                                                                                                                                                       
real    0m1.513s                                                                                                                                                                                       
user    0m1.560s                                                                                                                                                                                       
sys     0m0.039s                                                                                                                                                                                       
root@Debian-100-buster-64-minimal /data/test # time tail -n 300000 it/countrywide.csv | awk -v RS='"' 'NR % 2 == 0 { gsub(/\r?\n|\r/, " ") } { printf("%s%s", $0, "\r") }' > /dev/null                  
                                                                                                                                                                                                       
real    0m4.526s                                                                                                                                                                                       
user    0m4.524s                                                                                                                                                                                       
sys     0m0.174s                                                                                                                                                                                       
root@Debian-100-buster-64-minimal /data/test # time tail -n 400000 it/countrywide.csv | awk -v RS='"' 'NR % 2 == 0 { gsub(/\r?\n|\r/, " ") } { printf("%s%s", $0, "\r") }' > /dev/null                  
                                                                                                                                                                                                       
real    0m8.710s                                                                                                                                                                                       
user    0m8.682s                                                                                                                                                                                       
sys     0m0.197s                                                                                                                                                                                       
root@Debian-100-buster-64-minimal /data/test # time tail -n 500000 it/countrywide.csv | awk -v RS='"' 'NR % 2 == 0 { gsub(/\r?\n|\r/, " ") } { printf("%s%s", $0, "\r") }' > /dev/null                  
                                                                                                                                                                                                       
real    0m13.828s                                                                                                                                                                                      
user    0m13.889s                                                                                                                                                                                      
sys     0m0.271s                                                                                                                                                                                       
root@Debian-100-buster-64-minimal /data/test # time tail -n 500000 it/countrywide.csv | sed 's/$/,""/' | awk -v RS='"' 'NR % 2 == 0 { gsub(/\r?\n|\r/, " ") } { printf("%s%s", $0, "\r") }' > /dev/null 
                                                                                                                                                                                                       
real    0m0.199s                                                                                                                                                                                       
user    0m0.255s                                                                                                                                                                                       
sys     0m0.058s                                                                                                                                                                                       

```

**Comment by orangejulius** [comment]
Thanks for diving deep into it. My awk version is surprisingly different:

```
$ awk -W version
GNU Awk 4.2.1, API: 2.0
```

If you upgrade, do you see similar performance across the multiple tests?

**Comment by slvlirnoff** [comment]
installing `gawk` fixed it.

I suggest to install gawk in the docker image as a fix then.

**Comment by missinglink** [comment]
@slvlirnoff are you perchance on a Mac?

all the default POSIX tools for Mac are garbage, so I use `gawk`, `gsed` etc on my Mac but `awk`, `sed` etc on my Linux machine.
I think you'll find that `gawk` on the Mac is equivalent to `awk` on Ubuntu.

Maybe we can add something like this to the script for compatibility
https://github.com/pelias/docker/blob/master/pelias#L4-L15

**Comment by slvlirnoff** [comment]
@missinglink, no it was on debian and in the docker image from the project.

This could indeed but a small fix for people on mac or simply a line in the README that indicate a modern version of awk is recommended for good performance? With relevant apt/brew commands.

I'll close this merge request because I consider it properly fixed by installing recent awk, thanks @orangejulius for the change to docker.

**Pull request closed without merging**
