### PR TITLE
feat(demo): fix for jumbo markers on retina displays

### PR DESCRIPTION
**Pull request by missinglink**
fix for jumbo markers on retina displays

### CODE REVIEW

**Comment by orangejulius** [comment]
nice. what does this look like on a non-retna screen now? (i wish i had one handy at the moment)

**Comment by missinglink** [comment]
It looks the same on non-retina

**Comment by missinglink** [comment]
If you have no objections can you please approve the pull request to show that you are happy with the changes.

**Comment by missinglink** [comment]
I think a good workflow to tickets like this is to approve the PR in order to show that it's fundamentaly 'good'.

If you have a concern about, for instance, a test that could be run to confirm the bug on another system, then you could 'approve' the PR and also add a note.

This will allow for better use of time between team members located in different timezones.

The current workflow is frustrating for the original author and means that each PR must be addressed three times by the original author and twice from the reviewer.

**Comment by orangejulius** [comment]
Okay, just checking. The code looks like it removes functionality and I didn't have one handy. Good to hear it works everywhere

**Pull request merged**
